[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor -L defmt"

[env]
DEFMT_LOG="info"

[build]
rustflags = [
    # Required
    "-C", "link-arg=-Tlinkall.x",
    # Required for defmt
    "-C", "link-arg=-Tdefmt.x",
    # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
    # NOTE: May negatively impact performance of produced code
    "-C", "force-frame-pointers",
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
